parameters: {}
environment: {}
packages:
    - name: extract_transcript_from_audio
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: function
          binary: false
          main: ""
          runtime: python:default
          web: true
          webSecure: false
